### ISSUE TITLE
I get BGM but no video

### ISSUE THREAD

**Issue by sjx95** [halverneus/org.kde.video#1]
openSUSE Tumbleweed

I do as the guide, but now I have only sound but video.

I have ffmpeg, mplayer, and have try several type of video files such as H264, mpeg4, mpeg1, but nothing work.

So I'm thinking if I miss some package?

**Comment by halverneus** [comment]
Admittedly, I don't have any experience using openSUSE, but I will do what I can.

1. plasmashell --version

2. Have you installed media codecs from here? http://opensuse-community.org/

3. If you have VLC installed, does the video play correctly?

4. If it plays correctly in VLC: Menu -> Tools -> Codec Information and include the value of "Codec" where the value of "Type" is "Video".

5. Other things to try in the mean time: Use an application such as "Curlew" or "VLC" to convert the video to a different video format and retry.

6. If the video isn't private, you are welcome to send it to me and I can try it on my system.

**Comment by sjx95** [comment]
Thanks very much.
1 plasmashell 5.8.5
2 I have install all, but not work.
3 VLC can play this, I got vlc from packman
4 5 I had try to use some formats, now is mpgv/mpga in .mpg, video not work, but I can hear sounds. BTW I use ffmpeg to convert.
6 video @ http://himmel.tech/output.mpg    
-vcodc mpgv -acodc mpmga

**Comment by halverneus** [comment]
It does appear to be a codec issue. The video works on my system. Based on what you have installed, try the video in this Zip file:
[vid.zip](https://github.com/halverneus/org.kde.video/files/732739/vid.zip)
If that doesn't work, I have only other video converted to *.ogv.

**Comment by sjx95** [comment]
It works. And the h264/avc/flv format file works too.
I don't know why, I shutdown and go to bed last night, and now just turn on my laptop, without add any package...
Maybe it's needed to re-login or reboot to active this function? And it's not a decode problem, but kde problem?

BTW, this is the format now I can play:
flv/h264/avc [RAW]
mp4/h264/avc [ffmpeg -vcodec copy -acodec copy]
mpg/mpgv/mpga [ffmpeg] default mpg format
and vid.mp4 you sent.
