### ISSUE TITLE
Need to set a default video for all users

### ISSUE THREAD

**Issue by adocampo** [halverneus/org.kde.video#10]
Hello, 

I need to set a video lock screen and the same video for all my corporate machines. Installing this kind of "wallpaper" in /usr/share/plasma/wallpapers made accessible for all users to set a video wallpaper and lock screen.
I set a video (testvideo.mp4) lock screen for a user and did a `grep 'testvideo' * -R` inside the home of that user, but I didn't find any file where the configuration is suposed to be stored.
I would like to put the same video for all users/computers, is there any method I'm not seeing?

**Comment by halverneus** [comment]
I cat'd the appropriate file on my laptop below.

cat ~/.config/kscreenlockerrc 
[$Version]
update_info=kscreenlocker.upd:0.1-autolock

[Daemon]
Autolock=false
LockGrace=60
LockOnResume=false
Timeout=15

[Greeter]
Theme=org.kde.breezedark.desktop
WallpaperPlugin=org.kde.video

[Greeter][Wallpaper][org.kde.video][General]
Folder=file:///home/streets/Pictures/Wallpapers/
Muted=true
Video=file:///home/streets/Pictures/Wallpapers/Background Fire.mp4

**Comment by adocampo** [comment]
Thank you, my bad, I was grepping for the video on the wrong user... 🤦‍
