### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by JannisFuchs** [halverneus/org.kde.video#21]
I followed the steps correctly and every file is as it should be but there is no setting video.
I have the correct path

**Comment by Merodi** [comment]
vi .local/share/plasma/wallpapers/org.kde.video/contents/ui/main.qml

flushMode: VideoOutput.LastFrame // remove blinking
to
//flushMode: VideoOutput.LastFrame // remove blinking // notworking if QtMultimedia < 5.14

and reboot

**Comment by halverneus** [comment]
@Aguspy , did the fix from @Merodi fix your issue? I know a recent update relies on newer version of Qt. If you are using an older version of Qt, I recommend staying on changeset d22f26bec9c2cda448c086a5ab6780876d3ec1af .

**Comment by JannisFuchs** [comment]
As I tried to apply your changes I noticed that I had a completely different main.qml and that I had missing dependencies. But still thank you
